### ISSUE TITLE
I have a  question, need you to help

### ISSUE THREAD

**Issue by gaoplus** [arjunskumar/zed_aruco_marker_ros#1]
when I catkin_make this project, always display "no files  ArucoThreshold.h",I find you use this command "generate_dynamic_reconfigure_options(cfg/ArucoThreshold.cfg)", it will be generate xx.h file? and i always display some questions as follow:
make[2]: *** [/home/hl/test_ws/devel/include/aruco_ros/ArucoThresholdConfig.h] Error 126
CMakeFiles/Makefile2:2362: recipe for target 'zed_aruco_marker_ros/aruco_ros/aruco_ros/CMakeFiles/aruco_ros_gencfg.dir/all' failed
make[1]: *** [zed_aruco_marker_ros/aruco_ros/aruco_ros/CMakeFiles/aruco_ros_gencfg.dir/all] Error 2
Plesea help me, i want to finish zed detect aruco. look forward to your answers.

**Comment by arjunskumar** [comment]
@gaoplus please try chmod +x  filename.cfg and catkin_make again

**Comment by gaoplus** [comment]
Thank you very much，I got it，and successful catkin_make




------------------ 原始邮件 ------------------
发件人: "Arjun S Kumar"<notifications@github.com>; 
发送时间: 2019年6月26日(星期三) 中午1:44
收件人: "arjunskumar/zed_aruco_marker_ros"<zed_aruco_marker_ros@noreply.github.com>; 
抄送: "有点こ缌ソ唸"<295983859@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [arjunskumar/zed_aruco_marker_ros] I have a  question, need youto help (#1)




@gaoplus please try chmod +x  filename.cfg and catkin_make again
